require "plugins.configs.molokai"
require "plugins.configs.cmp"
require "plugins.configs.lsp"
require "plugins.configs.telescope"
require "plugins.configs.nvim-tree"
require "plugins.configs.comments"
require "plugins.configs.treesitter"
require "plugins.configs.gitsigns"
-- require "plugins.configs.bufferline"
